name: jh_debug
description: jh_debug The debugging plug-in above the APP. Easy-to-use console plugin, More feature details....
version: 0.3.10
homepage: https://github.com/tec8297729/jh_debug

environment:
  sdk: '>=2.2.2 <3.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
# sqflite: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
